# Generated by Django 6.1 on 2026-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('company', models.CharField(blank=True, default='', max_length=128, verbose_name='公司/品牌')),
                ('project_type', models.CharField(blank=True, default='', max_length=64, verbose_name='项目类型')),
                ('quantity', models.CharField(blank=True, default='', max_length=64, verbose_name='预计数量')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='交付城市')),
                ('budget', models.CharField(blank=True, default='', max_length=64, verbose_name='预算区间')),
                ('message', models.TextField(blank=True, default='', verbose_name='需求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '联系留言',
                'verbose_name_plural': '联系留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
