# Generated by Django 6.1 on 2026-08-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='contract',
        ),
    ]
