# Generated by Django 6.1 on 2026-08-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
    ]
